# Ansible playbook: Using custom ansible module written in golang
---
- hosts: all
  gather_facts: true
  become: yes
  roles:
    - { role: common, tags: ['common'] }
    - { role: googleauth, tags: ['tfa'] }
