# Playbook to configure prerequisites
---
  - name: Installing Epel Release
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present

  - name: Installing Google Authenticator
    yum:
      name: google-authenticator
      state: latest

  - name: No pass for newly created user
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'

  - name: Adding User
    user:
      name: google
      shell: /bin/bash
      create_home: yes
      generate_ssh_key: yes
      state: present
      groups: wheel

  - name: Adding vagrant user's authorization key to google user
    shell: |
      cp /home/vagrant/.ssh/authorized_keys /home/google/.ssh
      chown google:google /home/google/.ssh/authorized_keys
      exit 0
